# SPDX-FileCopyrightText: 2025 Ali Sajid Imami
#
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: MIT

# Accepted licenses by default
accepted = ["Apache-2.0", "MIT", "Unicode-3.0", "ISC", "MPL-2.0"]

# Do not ignore any dependencies
ignore-build-dependencies = false
ignore-dev-dependencies = false
ignore-transitive-dependencies = false

# Try to resolve any time clearlydefined.io marks something as NOASSERTION
filter-noassertion = true
